### PR TITLE
Canned crashes when using query string parameters

### PR DESCRIPTION
**Pull request by targoo**

### CODE REVIEW

**Comment by sideshowcoder** [comment]
Thanks for looking into this, I think that might be fixed by #96 but I'll take a look later today when I merge in the other. In the meanwhile mind providing a test case int `spec/...` to make sure this does not break again / is fixed?

**Comment by targoo** [comment]
https://github.com/sideshowcoder/canned/pull/96 probably going to fix it. cool. I'll work on the spec.

**Comment by sideshowcoder** [comment]
If you like to try with current master it should work, would be awesome to get a test case for it so!

**Comment by targoo** [comment]
i have added two more tests and it all working now on master.

Finished in 0.831 seconds
66 tests, 73 assertions, 0 failures, 0 skipped

**Comment by sideshowcoder** [comment]
👍

**Comment by sideshowcoder** [comment]
merged via 505157

**Comment by sideshowcoder** [comment]
merge via c246508

**Comment by sideshowcoder** [comment]
Ok 0.3.8 is out :)

**Pull request closed without merging**
