### PR TITLE
Issue 73 param matching bug

### PR DESCRIPTION
**Pull request by xdemocle**
Test #73 also passed

### CODE REVIEW

**Comment by xdemocle** [comment]
@sideshowcoder is this PR correct? You will join this branch on master later, correct?

Sorry, but i'm not super confident on opensource github workflow. ;-)

**Comment by sideshowcoder** [comment]
I'm happy with it ... looks good to me!

**Comment by sideshowcoder** [comment]
I'm not going to be able to run a publish to NPM today but see if I can get it out tomorrow. Also would be happy to hear what you are using canned for, this is always really interesting to me :)

**Comment by xdemocle** [comment]
No rushing at all for npm update, because im using my fork on local project package temporary.
I need to create from scratch a new portal but with very bad backend API  design.
Since im creating new endpoints and new features, I need a mockup json server running under my gulp project. I played around many tools, the most reliable was json-server but too limited, beside has also json storage allowing post requests.
But my first concern was recreating a folder structure for API, plus params matching feature... that's why I landed to your Canned. ;)
It was perfect but when I saw was not properly working, I got stuck again..... So, this time I preferred go through the problem because I believe is really valid for my case.

**Comment by sideshowcoder** [comment]
Nice to hear :) sounds like a great usecase basically the same problem I had when I created it. I merged all your changes so you can switch to the master if you like. If you have any more trouble I'm happy to help out if possible.

**Comment by xdemocle** [comment]
Ok, thank you... good to know. :+1: 

Be aware that this PR is for sideshowcoder:issue-73_param_matching_bug from xdemocle:issue-73_param_matching_bug, and not for your master.

That's why I asked which is the flow. I was not sure if I could PR from my xdemocle:issue-73_param_matching_bug to your sideshowcoder:master

**Pull request merged**
