### PR TITLE
this resolve issue #73 adding lodash as extra dependency, in order to…

### PR DESCRIPTION
**Pull request by xdemocle**
… use utility _.isMatch function to compare two param objects the passed one and the one inside the json file. Also forcing the params values to Strings

### CODE REVIEW

**Comment by sideshowcoder** [comment]
could you merge the test I created into your branch or copy it across somehow? If it passes I'm happy to merge :+1:

**Comment by sideshowcoder** [comment]
Oh and you can of course add yourself to the contributors in the README :)

**Comment by xdemocle** [comment]
sorry, I forgot to switch on branch: issue-73_param_matching_bug

**Comment by sideshowcoder** [comment]
No worries just copy of the test if that is easier...

**Comment by xdemocle** [comment]
Ok, I close this pull request and gonna open another with other branch: issue-73_param_matching_bug

**Pull request closed without merging**
