### PR TITLE
Enable canned to consider accept header

### PR DESCRIPTION
**Pull request by git-jiby-me**
This PR enabled canned to check accept header from request to identify which type
(js,json,txt,html) of file to respond with, if multiple file types
exists for the same request endpoint.

This PR enables this behaviour

- GET /test/testendpoint with application/json accept header => test/testendpoint.get.json
- GET /test/testendpoint with application/javascript accept header => test/testendpoint.get.js
- GET /test/testendpoint with text/plain accept header => test/testendpoint.get.txt
- GET /test/testendpoint with text/html accept header => test/testendpoint.get.html
- With any other accept header or none at all, canned with return first matching file, which can be any type

### CODE REVIEW

**Comment by sideshowcoder** [comment]
LGTM! Thanks for the PR, I'm merging this but I can't roll a new release right now, I will do so next week for the time being I guess you could install via github so.

**Comment by git-jiby-me** [comment]
@sideshowcoder no problems, i am currently using the library locally with the changes, once the new version is up, i will change to use the upstream version. By the way really helpful library, was really helpful in decoupling UI and Backend development and testing.

**Comment by sideshowcoder** [comment]
Thank you :) Happy to help!

**Comment by sideshowcoder** [comment]
Actually I just pushed out a version as I realized it is quick enough, so feel free to switch to 0.3.6 on npm.

**Comment by git-jiby-me** [comment]
@sideshowcoder Cool, very nice, thanks :+1:

**Pull request merged**
